# Generated by Django 6.1 on 2026-08-22 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('workspaces', '0002_workspace_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='workspaces.workspace'),
        ),
        migrations.DeleteModel(
            name='Workspace',
        ),
    ]
