# Generated by Django 6.1 on 2026-08-23 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectrepositorymapping'),
        ('projects', '0003_snippet_wikipage'),
    ]

    operations = [
    ]
