# Generated by Django 6.1 on 2026-08-23 02:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_username', models.CharField(blank=True, max_length=255, null=True)),
                ('github_user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('github_connection_status', models.CharField(choices=[('NOT_CONNECTED', 'Not Connected'), ('CONNECTED', 'Connected'), ('DISCONNECTED', 'Disconnected'), ('ERROR', 'Error')], default='NOT_CONNECTED', max_length=50)),
                ('github_connected_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('NOT_SYNCED', 'Not Synced'), ('PENDING', 'Pending'), ('SYNCING', 'Syncing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='NOT_SYNCED', max_length=50)),
                ('sync_error', models.TextField(blank=True, null=True)),
                ('historical_context', models.JSONField(blank=True, default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='developer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EngineeringEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='GITHUB', max_length=50)),
                ('repository_count', models.IntegerField(default=0)),
                ('repositories', models.JSONField(blank=True, default=dict)),
                ('technology_evidence', models.JSONField(blank=True, default=dict)),
                ('module_evidence', models.JSONField(blank=True, default=dict)),
                ('architecture_evidence', models.JSONField(blank=True, default=dict)),
                ('dependency_evidence', models.JSONField(blank=True, default=dict)),
                ('similar_work_evidence', models.JSONField(blank=True, default=dict)),
                ('contribution_summary', models.JSONField(blank=True, default=dict)),
                ('ownership_evidence', models.JSONField(blank=True, default=dict)),
                ('evidence_metadata', models.JSONField(blank=True, default=dict)),
                ('last_analyzed_at', models.DateTimeField(auto_now=True)),
                ('schema_version', models.CharField(default='v1', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engineering_evidence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'source'], name='developers__user_id_44fec3_idx')],
            },
        ),
    ]
