# Generated by Django 6.1 on 2026-08-23 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationscenario',
            name='duration_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simulationscenario',
            name='original_assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_assignment_simulations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='simulationscenario',
            name='unavailable_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_simulations', to=settings.AUTH_USER_MODEL),
        ),
    ]
