# Generated by Django 6.1 on 2026-08-22 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_due_date_task_priority'),
        ('tasks', '0003_delete_comment'),
    ]

    operations = [
    ]
