# Generated by Django 6.1 on 2026-08-23 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_merge_20260822_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='dependencies',
            field=models.ManyToManyField(blank=True, related_name='blocking_tasks', to='tasks.task'),
        ),
    ]
