# Generated by Django 5.2.17 on 2026-08-23 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0004_workspace_plan_paymenttransaction'),
        ('workspaces', '0005_enforce_single_owner'),
    ]

    operations = [
    ]
