# Generated by Django 6.1 on 2026-08-23 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0006_merge_20260823_1111'),
        ('workspaces', '0006_remove_unique_workspace_owner'),
    ]

    operations = [
    ]
